spring:
  cache:
    type: redis
    redis:
      time-to-live: 60000  # 1 minute TTL
  data:
    redis:
      port: 6379
      host: redis

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG

valid-denominations:
  denominations:
    - 0.01
    - 0.05
    - 0.1
    - 0.2
    - 0.5
    - 1
    - 2
    - 5
    - 10
    - 50
    - 100
    - 1000